
import { 
  LayoutDashboard, 
  Target, 
  ClipboardList, 
  Calendar as CalendarIcon, 
  PieChart, 
  Settings as SettingsIcon,
  Zap,
  Clock,
  AlertTriangle,
  TrendingUp,
  MessageSquare,
  Bot,
  Globe,
  Plus,
  Trash2,
  Lock,
  Calculator,
  Menu,
  X,
  Smile,
  Battery,
  User,
  LogOut,
  ChevronRight,
  Brain
} from 'lucide-react';

export const THEME = {
  BASE: '#0A0A0A',
  NEUTRAL_DARK: '#262626',
  NEUTRAL_MED: '#A3A3A3',
  PRIMARY: '#00C2A8', 
  SECONDARY: '#FF4B4B', 
  TERTIARY: '#FFD100', 
};

export const STRINGS = {
  'pt-BR': {
    appName: 'Lulenge',
    onboardingBtn: '[DEFINIR META]',
    onboardingTitle: 'Protocolo Lulenge',
    aiMode: 'Modo IA (SMART)',
    manualMode: 'Modo Manual',
    saveGoal: 'ATIVAR PROTOCOLO',
    dnaTitle: 'Perfil de Performance',
    infraTitle: 'Configurações de Sistema',
    workType: 'Tipo de Trabalho',
    chronotype: 'Cronotipo',
    skills: 'Habilidades',
    interests: 'Interesses',
    aiPersona: 'Tom da IA',
    customPrompt: 'Prompt Personalizado do Agente',
    lang: 'Idioma',
    timezone: 'Fuso Horário',
    autoTz: 'Fuso automático',
    weekStart: 'Início da Semana',
    perfGoal: 'Foco na Meta',
    perfMaint: 'Manutenção',
    perfWaste: 'Desperdício',
    dnaUpdated: 'Perfil Lulenge atualizado.',
    lockedSection: 'Defina uma Meta para desbloquear.',
    deleteGoal: 'Excluir Meta',
    noGoals: 'Nenhuma meta ativa.',
    newGoal: 'NOVA META',
    startNow: 'INICIAR AGORA',
    calcTitle: 'Calculadora de Esforço',
    missingReport: 'Dia sem registro',
  },
  'en-US': {
    appName: 'Lulenge',
    onboardingBtn: '[SET GOAL]',
    onboardingTitle: 'Lulenge Protocol',
    aiMode: 'AI Mode (SMART)',
    manualMode: 'Manual Mode',
    saveGoal: 'ACTIVATE PROTOCOL',
    dnaTitle: 'Performance Profile',
    infraTitle: 'System Settings',
    workType: 'Work Type',
    chronotype: 'Chronotype',
    skills: 'Skills',
    interests: 'Interests',
    aiPersona: 'AI Tone',
    customPrompt: 'Custom Agent Prompt',
    lang: 'Language',
    timezone: 'Timezone',
    autoTz: 'Auto Timezone',
    weekStart: 'Week Start',
    perfGoal: 'Goal Focus',
    perfMaint: 'Maintenance',
    perfWaste: 'Waste',
    dnaUpdated: 'Lulenge profile updated.',
    lockedSection: 'Set a Goal to unlock.',
    deleteGoal: 'Delete Goal',
    noGoals: 'No active goals.',
    newGoal: 'NEW GOAL',
    startNow: 'START NOW',
    calcTitle: 'Effort Calculator',
    missingReport: 'Unreported Day',
  }
};

export const ICONS = {
  Dashboard: LayoutDashboard,
  Goals: Target,
  Log: ClipboardList,
  Calendar: CalendarIcon,
  Performance: PieChart,
  Settings: SettingsIcon,
  Calculator,
  Zap,
  Clock,
  Alert: AlertTriangle,
  Growth: TrendingUp,
  Chat: MessageSquare,
  Agent: Bot,
  Globe,
  Plus,
  Trash: Trash2,
  Lock,
  Menu,
  X,
  Smile,
  Battery,
  User,
  LogOut,
  ChevronRight,
  Brain
};
